routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});

Route::post('/login', [LoginController::class, 'login']);
Route::resource('/company', CompanyController::class);
Route::resource('/employee', EmployeeController::class);

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;

    public function employees() {
        return $this->hasMany(Employee::class);
    }
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    public function company() 
    {
        return $this->belongsTo(Company::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUpdateCompanyRequest;
use App\Models\Company;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Storage;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $companies = Company::paginate(10);

        return view('company', [
            'companies' => $companies
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateUpdateCompanyRequest $request
     * @return Application|Redirector|RedirectResponse
     */
    public function store(CreateUpdateCompanyRequest $request)
    {
        $company =  new Company();
        $logo = $request->file('logo')->getClientOriginalName();
        $company->name = $request->get('name');
        $company->email = $request->get('email');
        $company->logo = $logo;
        $company->website = $request->get('website');

        Storage::disk('local')->put('public/'.$logo, file_get_contents($request->file('logo')));

        $company->save();

        return redirect('/company');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function show(int $id)
    {
        $company = Company::where('id', $id)->first();

        return view('company/index', [
            'company' => $company,
            'employees' => $company->employees
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CreateUpdateCompanyRequest  $request
     * @param int $id
     * @return Application|RedirectResponse|Redirector
     */
    public function update(CreateUpdateCompanyRequest $request, int $id)
    {
        $company = Company::where('id', $id)->first();
        $company->name = $request->get('name');
        $company->email = $request->get('email');
        $company->website = $request->get('website');

        $company->save();

        return redirect('/company/' . $company);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Application|Redirector|RedirectResponse
     */
    public function destroy(int $id)
    {
        try {

            Company::where('id', $id)->delete();
            return redirect('/company');
        } catch (\Exception $ex) {
            return redirect('/company');
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUpdateEmployeeRequest;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Redirector;

class EmployeeController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function show(int $id)
    {
        $employee = Employee::where('id', $id)->first();

        return view('employee/index', [
            'employee' => $employee,
        ]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateUpdateEmployeeRequest  $request
     * @return Application|Redirector|RedirectResponse
     */
    public function store(CreateUpdateEmployeeRequest $request)
    {
        $company = Company::where('id', $request->get('company_id'))->first();
        $employee = new Employee();

        $employee->first_name = $request->get('first_name');
        $employee->last_name = $request->get('last_name');
        $employee->email = $request->get('email');
        $employee->phone = $request->get('phone');

        $company->employees()->save($employee);

        return redirect(route('company.show', ['company' => $company]));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  CreateUpdateEmployeeRequest  $request
     * @param  int  $id
     * @return Application|RedirectResponse|Redirector
     */
    public function update(CreateUpdateEmployeeRequest $request, int $id)
    {
        $employee = Employee::where('id', $id)->first();

        $employee->first_name = $request->get('first_name');
        $employee->last_name = $request->get('last_name');
        $employee->email = $request->get('email');
        $employee->phone = $request->get('phone');

        $employee->save();
        $company = $employee->company;

        return redirect(route('company.show', ['company' => $company]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return RedirectResponse
     */
    public function destroy(int $id)
    {
        try {
            Employee::where('id', $id)->delete();
            return back();
        } catch (\Exception $ex) {
            return back();
        }
    }
}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LoginRequest;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class LoginController extends Controller
{
    public function login(LoginRequest $loginRequest)
    {
        $email = $loginRequest->get('email');
        $password = $loginRequest->get('password');

        $user = User::where('email', $email)->first();

        if(!isset($user)) {
            return back();
        }

        if(Hash::check($password, $user->password)) {
            Auth::attempt([
                'email' => $email,
                'password' => $password
            ]);
            return redirect('/company');
        }

        return back();
    }
}

resources/views/company.blade.php
@extends('home')
@section('content')

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Create Company
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="/company" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="company-name" class="col-form-label">Name:</label>
                            <input type="text" name="name" class="form-control" id="company-name">
                        </div>
                        <div class="form-group">
                            <label for="company-email" class="col-form-label">Email:</label>
                            <input type="email" name="email" class="form-control" id="company-email">
                        </div>
                        <div class="form-group">
                            <label for="company-logo" class="col-form-label">Logo:</label>
                            <input type="file" name="logo" class="form-control" id="company-logo">
                        </div>
                        <div class="form-group">
                            <label for="company-website" class="col-form-label">Website:</label>
                            <input type="text" name="website" class="form-control" id="company-website">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Logo</th>
                <th scope="col">Website</th>
            </tr>
        </thead>
        <tbody>
            @foreach($companies as $company)
                <tr>
                        <th scope="row">{{$company->id}}</th>
                        <td>
                            <a href="{{route('company.show', ['company' => $company])}}">
                                {{$company->name}}
                            </a>
                        </td>
                        <td>{{$company->email}}</td>
                        <td>{{$company->logo}}</td>
                        <td>{{$company->website}}</td>
                    <td>
                        <div>
                            <form action="{{route('company.destroy', ['company' => $company])}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-primary">
                                    Delete Company
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

@endsection

resources/views/company/index.blade.php
@extends('home')
@section('content')

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Edit Company
    </button>

    <!-- Company Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="company-name" class="col-form-label">Name:</label>
                            <input type="text" name="name" class="form-control" id="company-name" value="{{$company->name}}">
                        </div>
                        <div class="form-group">
                            <label for="company-email" class="col-form-label">Email:</label>
                            <input type="email" name="email" class="form-control" id="company-email" value="{{$company->email}}">
                        </div>
                        <div class="form-group">
                            <label for="company-logo" class="col-form-label">Logo:</label>
                            <input type="file" name="logo" class="form-control" id="company-logo">
                        </div>
                        <div class="form-group">
                            <label for="company-website" class="col-form-label">Website:</label>
                            <input type="text" name="website" class="form-control" id="company-website" value="{{$company->website}}">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" onclick="companyEdit({{$company->id}})">Save changes</button>
                    </div>
            </div>
        </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalEmployee">
        Create Employee
    </button>

    <!-- Employee Modal -->
    <div class="modal fade" id="exampleModalEmployee" tabindex="-1" aria-labelledby="exampleModalEmployeeLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="/employee" method="post">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="employee-first-name" class="col-form-label">First Name:</label>
                            <input type="text" name="first_name" class="form-control" id="employee-first-name">
                        </div>
                        <div class="form-group">
                            <label for="employee-last-name" class="col-form-label">Last Name:</label>
                            <input type="text" name="last_name" class="form-control" id="employee-last-name">
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="company_id" class="form-control" id="employee-company-id" value="{{$company->id}}">
                        </div>
                        <div class="form-group">
                            <label for="employee-email" class="col-form-label">Email:</label>
                            <input type="email" name="email" class="form-control" id="employee-email">
                        </div>
                        <div class="form-group">
                            <label for="employee-phone" class="col-form-label">Phone:</label>
                            <input type="text" name="phone" class="form-control" id="employee-phone">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Full name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
            </tr>
        </thead>
        <tbody>
            @foreach($employees as $employee)
                <tr>
                    <th scope="row">{{$employee->id}}</th>
                    <td>{{$employee->first_name}} {{$employee->last_name}}</td>
                    <td>{{$employee->email}}</td>
                    <td>{{$employee->phone}}</td>
                    <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalEmployee-{{$employee->id}}">
                        Edit Employee
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModalEmployee-{{$employee->id}}" tabindex="-1" aria-labelledby="exampleModalEmployeeLabel-{{$employee->id}}" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                    <div class="modal-body">
                                        <input type="hidden" id="_token" value="{{csrf_token()}}">
                                        <div class="form-group">
                                            <label for="employee-first-name" class="col-form-label">First Name:</label>
                                            <input type="text" name="first_name" class="form-control" id="employee-{{$employee->id}}-first-name" value="{{$employee->first_name}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="employee-last-name" class="col-form-label">Last Name:</label>
                                            <input type="text" name="last_name" class="form-control" id="employee-{{$employee->id}}-last-name" value="{{$employee->last_name}}">
                                        </div>
                                        <div class="form-group">
                                            <input type="hidden" name="company_id" class="form-control" id="employee-company-id" value="{{$company->id}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="employee-email" class="col-form-label">Email:</label>
                                            <input type="email" name="email" class="form-control" id="employee-{{$employee->id}}-email" value="{{$employee->email}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="employee-phone" class="col-form-label">Phone:</label>
                                            <input type="text" name="phone" class="form-control" id="employee-{{$employee->id}}-phone" value="{{$employee->phone}}">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-primary" onclick="handleSubmitForm({{$employee->id}})" data-id="{{$employee->id}}">Save</button>
                                    </div>
                            </div>
                        </div>
                    </div>
                        <div>
                            <form action="{{route('employee.destroy', ['employee' => $employee])}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-primary">
                                    Delete Employee
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <script type="text/javascript">
            function handleSubmitForm(id) {
                const formData = {
                    first_name: $("#employee-" + id + "-first-name").val(),
                    last_name: $("#employee-" + id + "-last-name").val(),
                    email: $("#employee-" + id + "-email").val(),
                    phone: $("#employee-" + id + "-phone").val()
                };

                $.ajax({
                    type: "PUT",
                    url: '/employee/' + id,
                    data: formData,
                    success: function (response) {
                        console.log("Request successful:", response);
                        $("#exampleModalEmployee-"+id).modal("hide");
                    },
                    error: function (error) {
                        console.error(error);
                    }
                });
            }

            function companyEdit(id) {
                const formData = new FormData();

                formData.append("name", $("#company-name").val());
                formData.append("email", $("#company-email").val());
                formData.append("website", $("#company-website").val());

                const logoFileInput = document.getElementById("company-logo");
                if (logoFileInput.files.length > 0) {
                    formData.append("logo", logoFileInput.files[0]);
                }


                $.ajax({
                    type: "PUT",
                    url: '/company/' + id,
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        console.log("Request successful:", response);
                        $("#exampleModalEmployee-"+id).modal("hide");
                    },
                    error: function (error) {
                        console.error(error);
                    }
                });
            }
    </script>

@endsection

resources/views/home.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
      <meta name="csrf-token" content="{{ csrf_token() }}" />

  </head>
  <body>

    @yield('content')
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
    <script>
        window.onload = () => {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        }
    </script>
  </body>
</html>

resources/views/login.blade.php
@extends('home')

@section('content')

    <form action="/login" method="post">
        @csrf
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1" name="password">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

@endsection